baseURL = "/"
languageCode = "de-de"

title = "Familie-Blume"
theme = "aerial"

[params]
  name = "Famile Blume"
  about = "Sicherheits Chef &nbsp;&bull;&nbsp; Cyborg &nbsp;&bull;&nbsp; Nie darum gebeten"
  copyright = "OBlume"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "a"
  favicon = "favicon.ico"

[[params.social]]
  medium = "Doc"
  icon = "file-text-o"
  link = "https://doc.blume.goip.de"

[[params.social]]
  medium = "GitLab"
  icon = "gitlab"
  link = "https://dev.blume.goip.de/gitlab/"

[[params.social]]
  medium = "QNAP"
  icon = "server"
  link = "https://dev.blume.goip.de/"

[[params.social]]
  medium = "RPi Health check"
  icon = "heartbeat"
  link = "https://dev.blume.goip.de/rpimonitor/status.html"

[[params.social]]
  medium = "RPi Health check"
  icon = "heartbeat"
  link = "http://server1:8080"

[[params.social]]
  medium = "RPi Health check"
  icon = "heartbeat"
  link = "http://server1:8888"

[[params.social]]
  medium = "Haselmaus"
  icon = "header"
  link = "https://haselmaus.spdns.de:23443"
