baseURL = "/"
languageCode = "de-de"

title = "Familie-Blume"
theme = "aerial"

[params]
  name = "Famile Blume"
  about = "Sicherheits Chef &nbsp;&bull;&nbsp; Cyborg &nbsp;&bull;&nbsp; Nie darum gebeten"
  copyright = "OBlume"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "a"
  favicon = "favicon.ico"

[[params.social]]
  medium = "Doc"
  icon = "file-text-o"
  link = "http://doc.blume.goip.de"

[[params.social]]
  medium = "Develop"
  icon = "cogs"
  link = "http://dev.blume.goip.de"